  name: InstantRespawn
  main: thebigsmileXD\InstantRespawn\Main
  version: 0.3.2
  api: 1.0.0
  load: POSTWORLD
  authors: [thebigsmileXD]
  prefix: "InstantRespawn"
  commands:
   instantrespawn:
    description: "Commands for InstantRespawn"
    usage: "/instantrespawn <list|add <worldname>|remove <worldname>"
    permission: instantrespawn.command
  permissions:
    instantrespawn.command:
      description: Permission for /instantrespawn commands.
      default: op